apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: 065693560547.dkr.ecr.eu-west-1.amazonaws.com/clothing-model-images:gateway-001
        resources:
          limits:
            memory: "512Mi"
            cpu: "200m"
        ports:
        - containerPort: 9600
        env:
        - name: TF_CLOTHING_MODEL_HOST
          value: tf-serving-clothing-model.default.svc.cluster.local:8500
