apiVersion: apps/v1
kind: Deployment
metadata:
  name: tf-serving-clothing-model
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tf-serving-clothing-model
  template:
    metadata:
      labels:
        app: tf-serving-clothing-model
    spec:
      containers:
      - name: tf-serving-clothing-model
        image: 065693560547.dkr.ecr.eu-west-1.amazonaws.com/clothing-model-images:xception_v1_model-001
        resources:
          limits:
            memory: "1024Mi"
            cpu: "1"
        ports:
        - containerPort: 8500
